---
- name : Undeploy proxy {{ appName }} - {{ item }}
  uri :
    url :"{{api_server}}/v1/organizations/{{apigee_org}}/environments/{{apigee_env}}/apis/cf-{{ appName }}-{{ item }}.{{ cfDomain }}/revisions/{{proxy_version}}/deployments"
    method : "DELETE"
    user : " {{ apigee_user }} "
    password : "{{ apigee_password }}"
    force_basic_auth : yes 
    status_code : 404,200,201,202

- name : Delete proxy {{ appName }} - {{ item }}
  uri :
    url : "{{api_server}}/v1/organizations/{{apigee_org}}/apis/cf-{{ appName }}-{{ item }}.{{ cfDomain }}
    method : "DELETE"
    user : " {{ apigee_user }} "
    password : "{{ apigee_password }}"
    force_basic_auth : yes 
    status_code : 404,200,201,202



