---
- name : Print command to Undeploy Proxy 
  debug: 
    msg  : "{{ mgmt_api_uri }}/organizations/{{ apigee_org }}/environments/{{apigee_env}}/apis/cf-{{ appName }}-{{ item }}.{{ cfDomain }}/revisions/{{ proxy_version }}/deployments"

- name : Print command to Delete Proxy  
  debug: 
    msg : "{{ mgmt_api_uri }}/organizations/{{ apigee_org }}/apis/cf-{{ appName }}-{{ item }}.{{ cfDomain }}"

- name : Undeploy proxy {{ appName }} - {{ item }}
  uri :
    url : "{{ mgmt_api_uri }}/organizations/{{ apigee_org }}/environments/{{apigee_env}}/apis/cf-{{ appName }}-{{ item }}.{{ cfDomain }}/revisions/{{ proxy_version }}/deployments"
    method : "DELETE"
    HEADER_Authorization : "Basic b3Bka0BhcGlnZWUuY29tOlNlY3JldDEyMw=="
    status_code : 200,404

- name : Delete proxy {{ appName }} - {{ item }}
  uri :
    url : "{{ mgmt_api_uri }}/organizations/{{ apigee_org }}/apis/cf-{{ appName }}-{{ item }}.{{ cfDomain }}"
    method : "DELETE"
    HEADER_Authorization : "Basic b3Bka0BhcGlnZWUuY29tOlNlY3JldDEyMw=="
    status_code : 404,200,201,202



