---      
- name: UnBind application - {{ item }}
  command:  cf unbind-route-service apps.apigee-cf.com org --hostname app-{{ item }} 
  
- name: Remove application - {{ item }}
  command: cf delete app-{{ item }} -f 