---      
- name: UnBind application 
  command:  cf unbind-route-service apps.apigee-cf.com org --hostname {{ app_name }}-{{ item }} 
  
- name: Remove application
  command: cf delete {{ app_name }}-{{ item }} -f 