---      
- name: UnBind application 
  command:  cf unbind-route-service apps.apigee-cf.com org --hostname hello-{{ item }} 
  args:
    chdir: roles/helloapp/files/sample-api 

- name: Remove application
  command: cf delete hello-{{ item }} -f -r 
  args:
    chdir: roles/helloapp/files/sample-api  